# Generated by Django 6.0.1 on 2026-01-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantform', '0002_alter_course_id_alter_enrollment_id_alter_lesson_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
