# Generated by Django 6.0.1 on 2026-01-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantform', '0003_module_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='lesson_videos/'),
        ),
    ]
